[package]
name = "ubench"
version = "0.1.0"
edition = "2021"
rust-version = "1.62.0"

[dependencies]

[package.metadata.docs.rs]
targets = [""]
rustdoc-args = ["--cfg", "docs"]
all-features = true
default-target = ""
